# Practicing data cleaning Machine learning

## Step 0 : Importing important dependencies

In [1]:
# Core ML libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Data collection 

We will check different dataset and then we will select the one which will help me learn it properly

In [5]:
flower_df = pd.read_csv("D:\Robotics\Learn Machine Learning with RoboZe\Dataset used in this series\iris_data.csv")

In [7]:
placement_df = pd.read_csv("D:\Robotics\Learn Machine Learning with RoboZe\Dataset used in this series\Placement_Dataset.csv")

In [10]:
df = pd.read_csv("D:\Robotics\Learn Machine Learning with RoboZe\data\messy_customer_data.csv")

In [8]:
placement_df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [6]:
flower_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
flower_df.info

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [11]:
df

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.00,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.00,NaN,user4mail.com,9234603292,USA
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,NaN,M,200.0,Delhi,NaN,17/09/2020,NaN,10.0,NaN,9669860802,UK
9996,NaN,Ankit,female,-5.0,Chennai,not_a_date,23/03/2022,NaN,5.0,NaN,0,USA
9997,9998,NaN,female,35.0,Kolkata,24/05/2022,missing,-999.00,-1.0,NaN,NaN,USA
9998,NaN,Pooja,F,24.0,Chennai,not_a_date,NaN,NaN,-1.0,user9998mail.com,9716472962,UK
9999,10000,Kiran,F,-5.0,Hyderabad,03/07/2022,21/03/2025,2254.23,NaN,user9999mail.com,0,USA

In [13]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

## Analyse the data

Identify all the problems in the dataset

In [15]:
df.shape

(10000, 12)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          7621 non-null   object
 1   Name                8342 non-null   object
 2   Gender              7545 non-null   object
 3   Age                 7424 non-null   float64
 4   City                8870 non-null   object
 5   Signup_Date         7471 non-null   object
 6   Last_purchase_date  6714 non-null   object
 7   purchase_amount     4967 non-null   float64
 8   feedback_score      7538 non-null   float64
 9   email               4934 non-null   object
 10  Phone_number        7556 non-null   object
 11  Country             8296 non-null   object
dtypes: float64(3), object(9)
memory usage: 937.6+ KB

In [14]:
df.describe()

               Age  purchase_amount  feedback_score
count  7424.000000      4967.000000     7538.000000
mean     78.904364       713.654008        4.008092
std      87.817619      2002.187228        4.619336
min      -5.000000      -999.000000       -1.000000
25%      -5.000000      -999.000000       -1.000000
50%      43.000000      -999.000000        3.000000
75%     200.000000      2437.600000       10.000000
max     200.000000      4998.670000       10.000000

In [16]:
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           2529
Last_purchase_date    3286
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [17]:
# Checking percentage of missing values

df.isnull().sum()/len(df)*100

CustomerID            23.79
Name                  16.58
Gender                24.55
Age                   25.76
City                  11.30
Signup_Date           25.29
Last_purchase_date    32.86
purchase_amount       50.33
feedback_score        24.62
email                 50.66
Phone_number          24.44
Country               17.04
dtype: float64